name: 'seqflow action'
description: ''
inputs:
  callback:
    description: 'script to be executed on each version branch'
    required: true
runs:
  using: 'composite'
  steps: 
    - run: |
        SEQFLOW_CALLBACK='${{inputs.callback}}'
        . $GITHUB_ACTION_PATH/action.sh
      shell: bash
